package com.mycompany.grabberrasskazov.models;
// Generated Jan 4, 2015 12:47:44 AM by Hibernate Tools 4.3.1



/**
 * StoriesToCategoriessRelations generated by hbm2java
 */
public class StoriesToCategoriessRelations  implements java.io.Serializable {


     private Integer id;
     private Stories stories;
     private StoryCategories storyCategories;

    public StoriesToCategoriessRelations() {
    }

    public StoriesToCategoriessRelations(Stories stories, StoryCategories storyCategories) {
       this.stories = stories;
       this.storyCategories = storyCategories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Stories getStories() {
        return this.stories;
    }
    
    public void setStories(Stories stories) {
        this.stories = stories;
    }
    public StoryCategories getStoryCategories() {
        return this.storyCategories;
    }
    
    public void setStoryCategories(StoryCategories storyCategories) {
        this.storyCategories = storyCategories;
    }




}


