package com.mycompany.grabberrasskazov.models;
// Generated Jan 4, 2015 12:47:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * StoryWriters generated by hbm2java
 */
public class StoryWriters  implements java.io.Serializable {


     private Integer id;
     private String writerName;
     private String writerEmail;
     private String oldId;
     private Set<StoriesToWritersRelations> storiesToWritersRelationses = new HashSet<StoriesToWritersRelations>(0);

    public StoryWriters() {
    }

    public StoryWriters(String writerName, String writerEmail, String oldId, Set<StoriesToWritersRelations> storiesToWritersRelationses) {
       this.writerName = writerName;
       this.writerEmail = writerEmail;
       this.oldId = oldId;
       this.storiesToWritersRelationses = storiesToWritersRelationses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getWriterName() {
        return this.writerName;
    }
    
    public void setWriterName(String writerName) {
        this.writerName = writerName;
    }
    public String getWriterEmail() {
        return this.writerEmail;
    }
    
    public void setWriterEmail(String writerEmail) {
        this.writerEmail = writerEmail;
    }
    public String getOldId() {
        return this.oldId;
    }
    
    public void setOldId(String oldId) {
        this.oldId = oldId;
    }
    public Set<StoriesToWritersRelations> getStoriesToWritersRelationses() {
        return this.storiesToWritersRelationses;
    }
    
    public void setStoriesToWritersRelationses(Set<StoriesToWritersRelations> storiesToWritersRelationses) {
        this.storiesToWritersRelationses = storiesToWritersRelationses;
    }




}


