package com.mycompany.grabberrasskazov.models;
// Generated Jan 4, 2015 12:47:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stories generated by hbm2java
 */
public class Stories  implements java.io.Serializable {


     private Integer storyId;
     private String storyName;
     private String storyText;
     private Date dateAdded;
     private Float size;
     private String oldId;
     private Set<StoriesToWritersRelations> storiesToWritersRelationses = new HashSet<StoriesToWritersRelations>(0);
     private Set<StoriesToCategoriessRelations> storiesToCategoriessRelationses = new HashSet<StoriesToCategoriessRelations>(0);

    public Stories() {
    }

    public Stories(String storyName, String storyText, Date dateAdded, Float size, String oldId, Set<StoriesToWritersRelations> storiesToWritersRelationses, Set<StoriesToCategoriessRelations> storiesToCategoriessRelationses) {
       this.storyName = storyName;
       this.storyText = storyText;
       this.dateAdded = dateAdded;
       this.size = size;
       this.oldId = oldId;
       this.storiesToWritersRelationses = storiesToWritersRelationses;
       this.storiesToCategoriessRelationses = storiesToCategoriessRelationses;
    }
   
    public Integer getStoryId() {
        return this.storyId;
    }
    
    public void setStoryId(Integer storyId) {
        this.storyId = storyId;
    }
    public String getStoryName() {
        return this.storyName;
    }
    
    public void setStoryName(String storyName) {
        this.storyName = storyName;
    }
    public String getStoryText() {
        return this.storyText;
    }
    
    public void setStoryText(String storyText) {
        this.storyText = storyText;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Float getSize() {
        return this.size;
    }
    
    public void setSize(Float size) {
        this.size = size;
    }
    public String getOldId() {
        return this.oldId;
    }
    
    public void setOldId(String oldId) {
        this.oldId = oldId;
    }
    public Set<StoriesToWritersRelations> getStoriesToWritersRelationses() {
        return this.storiesToWritersRelationses;
    }
    
    public void setStoriesToWritersRelationses(Set<StoriesToWritersRelations> storiesToWritersRelationses) {
        this.storiesToWritersRelationses = storiesToWritersRelationses;
    }
    public Set<StoriesToCategoriessRelations> getStoriesToCategoriessRelationses() {
        return this.storiesToCategoriessRelationses;
    }
    
    public void setStoriesToCategoriessRelationses(Set<StoriesToCategoriessRelations> storiesToCategoriessRelationses) {
        this.storiesToCategoriessRelationses = storiesToCategoriessRelationses;
    }




}


